export const SCAN_SERIAL_TO_REGISTER = 'SCAN_SERIAL_TO_REGISTER';
export const CALL_CUSTOMER_CARE = 'CALL_CUSTOMER_CARE';
export const REGISTER = 'REGISTER';
export const HOME_WITH_PROFILE = 'HOME_WITH_PROFILE';
export const CUSTOMER_PROFILE = 'CUSTOMER_PROFILE';
export const ON_TOGGLE = 'ON_TOGGLE';
